# Generated by Django 5.0.2 on 2024-02-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produit',
        ),
    ]
