# Generated by Django 5.0.2 on 2024-03-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_tag_produit_date_debut_produit_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
