# Generated by Django 5.0.2 on 2024-03-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_produit_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nom',
            new_name='Nom',
        ),
    ]
