# Generated by Django 5.0.2 on 2024-02-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='date_created',
            new_name='Date_creation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='number',
        ),
        migrations.AddField(
            model_name='client',
            name='Nom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
