# Generated by Django 5.0.2 on 2024-02-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_address_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
