# Generated by Django 5.0.2 on 2024-02-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_commande_client_commande_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='benefices',
        ),
    ]
