# Generated by Django 5.0.2 on 2024-03-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_remove_commande_benefices'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('en instance', 'En instance'), ('non livré', 'Non livré'), ('livré', 'Livré')], max_length=200, null=True),
        ),
    ]
