# Generated by Django 5.0.2 on 2024-03-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_alter_commande_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('non livré', 'non livré'), ('livré', 'Livré')], max_length=200, null=True),
        ),
    ]
