# Generated by Django 5.0.2 on 2024-03-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0007_alter_commande_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='nombre',
        ),
    ]
