# Generated by Django 5.0.2 on 2024-03-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0008_remove_commande_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Nom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
