# Generated by Django 5.0.2 on 2024-03-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0011_commande_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('en_instance', 'En instance'), ('non_livre', 'Non livré'), ('livre', 'Livré')], max_length=200, null=True),
        ),
    ]
